### PR TITLE
API Rework

### LINKED ISSUE #25: Check original encoded strings against the signature
To verify the UCAN signature, at the moment we're decoding the base64 parts of the UCAN into JSON, then stringify that JSON back into base64 and then bytes, and then check those bytes against the signature.

This process is likely to be lossy in unexpected ways. `JSON.stringify(JSON.parse(x)) === x` doesn't hold for all values of `x`.

This results in some UCANs being rejected even though their signatures are correct.

Relevant code:
https://github.com/ucan-wg/ts-ucan/blob/6a75d56fbcdc992cb730e95140185ff3fb9e429a/src/token.ts#L204-L210

I think we should change the API somewhat to fix this issue:
```ts
async function checkSignature(string: encodedUcan): Promise<boolean>
function decode(string: encodedUcan): UCAN
async function validate(string: encodedUcan): Promise<UCAN> { // throws if invalid? Or just returns Result<>
  // ...
  ... = await checkSignature(encodedUcan)
  // ...
  const ucan = decode(encodedUcan)
  // ...
}
```

### PR DESCRIPTION
**Pull request by matheus23**
Fixes #25 

This PR splits the API into a lower-level and a high-level API.

The low-level API is only concerned with "one" level of UCANs. I.e. it doesn't look through a whole ucan chain. It will only parse or encode *one* layer at a time.

The high-level API is concerned with UCANs as a whole. It'll parse UCANs in to a recursive structure and provide tools to extract what capabilities a UCAN encompasses. These tools are meant to be general enough to support custom use-cases. And this is the layer I'm looking to add support for features in the spirit of #20 and #21.

I consider the rework of the lower-level API pretty much done right now.
The main changes are:
* All functions are now based on the outer-most layer of a UCAN passed as an argument or only construct one layer of a UCAN
* I've combined `token.isValid` and `token.decode` into one function `token.validate`. This is to fix #25, by doing the signature checking on the original encoding.
* I've removed attenuation checking from the low level API for a couple of reasons:
  * Attenuation checking so far was based on structural JSON-equivalence. However, the semantics can be different for each kind of capability.
  * Even if the above semantics is the right one for *some* cases (e.g. a simple "allow sending email" semantic), it's still implemented incorrectly. An attenuation is valid even if it appears in a child, but not in a parent. However, we consider it to be "originated" by the issuer from the UCAN that first mentioned said capability.
  * Due to the last point, we can't just validate attenuations, but for each capability we need to determine the "originator" of that capability. The spec calls this "created/owned/originated by the `iss` DID". So again, we can't just validate, we need to parse.
  * Also, we just need to look multiple layers deep into a UCAN to validate the attenuation, so it's pushed up into the "high-level" API.

The high level API isn't done yet, thus this is only a draft.

The beginnings of it are in `chain.ts` and `attenuation.ts`.

In `chain.ts` there's an opaque class `Chained` (naming is hard please help). It encapsulates a parsed UCAN chain with both its original encoding as well as a decoded internal representation. Constructing it will verify the UCAN chains, i.e. that all `aud` and `iss` fields match up.

In `attenutation.ts` I've implemented a simple `emailCapabilities` function which extracts information about what a UCAN claims it has gotten capability for. It nicely illustrates how we need to parse out information out of a complete UCAN chain to arrive at what exactly a UCAN is capable of.

### CODE REVIEW

**Comment by matheus23** [comment]
Reduced the scope for this PR.

Capabilities will be another PR.

This includes:
- Single-layer low-level `validate` function combining `encode` and `isValid`. Fixes #25 
- Added `chain.ts` as a way to interact with UCANs that are parsed deeply.

**Comment by dholms** [comment]
just saw this @matheus23 ill take a more in depth look here in the next couple days :eyes:

File: src/base64.ts [hunk 1]
```diff
@@ -1,18 +0,0 @@
-import * as uint8arrays from "uint8arrays"
```
Comment (dholms) [inline src/base64.ts:1]: thank you, i hated this file :joy:

File: src/did/prefix.ts [hunk 2]
```diff
@@ -31,21 +31,21 @@ export const parseMagicBytes = (prefixedKey: Uint8Array): {
...
 
   // EDWARDS
   } else if (hasPrefix(prefixedKey, EDWARDS_DID_PREFIX)) {
     return {
       keyBytes: prefixedKey.slice(EDWARDS_DID_PREFIX.byteLength),
-      type: 'ed25519'
+      type: "ed25519"
     }
 
   // EDWARDS
```
Comment (dholms) [inline src/did/prefix.ts:44]: just saw this (it's my fault lol), this should be bls^^

File: src/token.ts [hunk 3]
```diff
@@ -194,34 +172,93 @@ export const isTooEarly = (ucan: Ucan): boolean => {
...
-  if (!ucan.payload.prf) return true
+  if (!isUcanHeader(header)) {
+    throw new Error(`Can't parse UCAN header: ${encodedHeader}: Invalid format.`)
+  }
+  if (!isUcanPayload(payload)) {
+    throw new Error(`Can't parse UCAN payload. ${encodedPayload}: Invalid format.`)
+  }
+
+  if (checkSignature) {
+    const data = uint8arrays.fromString(`${encodedHeader}.${encodedPayload}`, "ascii")
```
Comment (dholms) [inline src/token.ts:214]: `sign` just does `uint8arrays.fromString(`${encodedHeader}.${encodedPayload}`)` which defaults to `utf8` instead of `ascii`.

all of base64 is both ascii & utf8 so I don't think this should cause any issues, but maybe just standardize on utf8 to be safe?

File: src/chain.ts [hunk 4]
```diff
@@ -0,0 +1,169 @@
+import { Ucan, Capability, Fact } from "./types"
+import * as token from "./token"
+
+
+/**
+ * Represents a deeply verified chain of UCANs.
+ *
+ * These chains can actually be trees sometimes (if a ucan has >1 proofs).
+ */
+export class Chained {
```
Comment (dholms) [inline src/chain.ts:10]: I like the class-based semantics here & think it would fit well in token also.

I often find myself wanting to do
```ts
const token = ucan.build(....)
const encoded = token.encode()
// instead of
const encoded = ucan.encode(token)
```

File: src/did/prefix.ts (hunk 2 above)
Comment (dholms) [reply src/did/prefix.ts:44]: (the comment that is)

File: src/chain.ts [hunk 5]
```diff
@@ -0,0 +1,169 @@
...
+    static async fromToken(encodedUcan: string, options?: token.ValidateOptions): Promise<Chained> {
+        const ucan = await token.validate(encodedUcan, options)
+
+        // parse proofs recursively
+        const proofs = await Promise.all(ucan.payload.prf.map(encodedPrf => Chained.fromToken(encodedPrf, options)))
+
+        // check sender/receiver matchups. A parent ucan's audience must match the child ucan's issuer
+        const incorrectProof = proofs.find(proof => proof.audience() !== ucan.payload.iss)
+        if (incorrectProof != null) {
+            throw new Error(`Invalid UCAN: Audience ${incorrectProof.audience()} doesn't match issuer ${ucan.payload.iss}`)
```
Comment (dholms) [inline src/chain.ts:42]: assuming some way of doing attenuation checks are coming in the next one :eyes:

**Review by dholms — APPROVED** [review]
Looks good to me :+1: 

The only thing that stuck out to me is the utf8 vs ascii thing

File: src/did/prefix.ts (hunk 2 above)
Comment (matheus23) [reply src/did/prefix.ts:44]: Ah yeah right. Lemme fix that

File: src/token.ts (hunk 3 above)
Comment (matheus23) [reply src/token.ts:214]: Right. I was going back-and-forth with this a little.
It should definitely be the same in `sign` and `validate`! Good catch.
But I'm still not sure whether it should be `ascii` or `utf8`. Technically non-ascii would have already errored before (since we're both splitting on "." and then parsing the elements using base64url). But of course, that's not really obvious and someone might accidentally change that piece of code/copy it somewhere unsafe. :thinking: I'll take a look at what `ascii` and what `utf8` do. I'd prefer the one that fails less.

Comment (matheus23) [reply src/token.ts:214]: Okay, neither errors out really. And because `utf8` uses `TextDecoder` underneath which operates on whole strings at a time & is built into the VM, wheras `ascii` iterates through the string and calls `charCodeAt`, it's much slower.
So I'll just remove the `ascii` and let both work with `utf8`!

File: src/chain.ts (hunk 4 above)
Comment (matheus23) [reply src/chain.ts:10]: Yeah! They're somewhat syntactically nicer, I agree.
I usually don't like classes in javascript, because to test whether something is a class you'd use `instanceof`. But often bundlers get in your way and you can often accidentally end up with some code in multiple places. E.g. you've got `(await import("ucans")).Chained != (await import("ucans/chained")).Chained` and as such your `instanceof` can break with one of them.

In this case I still went with it. I'm *still* not sure whether that's a good idea, but the main reason was that I wanted something with conceptually private data. `Chained` is supposed to be opaque, that's not the case with the token stuff in `token.ts`.

I've done some further work on the indexer yesterday evening and realized that I *do* want to have a builder API. That one will make use of class-based dot syntax such that building UCANs will be much more fun. :)

File: src/chain.ts (hunk 5 above)
Comment (matheus23) [reply src/chain.ts:42]: Yep :100:

**Comment by matheus23** [comment]
Thanks for the review and great catch with the utf8 vs. ascii stuff!
